export const GET_USERS = 'user/get';
export const UPDATE_USER = 'user/update';
export const GET_USER_BY_USERNAME = 'user/get-by-username';
export const CHECK_REVIEWER_VALIDITY = 'user/check-reviewer-validity'; // check if the user already reviewed
export const WRITE_USER_REVIEW = 'user/write-review';
export const GET_USER_REVIEWS = 'user/get-reviews';
export const CHECK_USER_FOLLOW = 'user/check-follow';
export const FOLLOW_USER = 'user/follow';
export const GET_USER_FOLLOWS = 'user/get-follows';
